// @vitest-environment node

import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import sourceContract from "../../config/phase-2/source-contract.json";

const schema = readFileSync(
  new URL("../../prisma/schema.prisma", import.meta.url),
  "utf8",
);
const migration = readFileSync(
  new URL(
    "../../prisma/migrations/20260715135204_phase_2_initial/migration.sql",
    import.meta.url,
  ),
  "utf8",
);

const TECHNICAL_COLUMNS = [
  "lecturer_uid",
  "record_uid",
  "snapshot_id",
  "version_no",
  "identity_status",
  "source_row_number",
  "source_row_checksum",
  "source_import_run_id",
  "source_submission_id",
  "approval_unit",
  "origin",
  "approved_by",
  "approved_at",
  "created_at",
] as const;

describe("Phase 2 database schema", () => {
  it("keeps exactly the contracted business columns in ueb_core_data", () => {
    const tableSql = migration.match(
      /CREATE TABLE "ueb_core_data" \(([\s\S]*?)\n\);/u,
    )?.[1];
    expect(tableSql).toBeDefined();

    const actualColumns = [
      ...(tableSql ?? "").matchAll(/^\s+"([^"]+)"\s/gmu),
    ].map(([, column]) => column);
    const businessColumns = sourceContract.column_mapping.map(
      ({ postgresql_column: column }) => column,
    );

    expect(actualColumns).toEqual([...businessColumns, ...TECHNICAL_COLUMNS]);
    expect(businessColumns).toHaveLength(
      sourceContract.exact_business_column_count,
    );
  });

  it("maps every non-stt business column from the contract", () => {
    for (const column of sourceContract.column_mapping.slice(1)) {
      expect(schema).toContain(`@map("${column.postgresql_column}")`);
    }
    expect(schema).toMatch(/\bstt Int @id @default\(autoincrement\(\)\)/u);
  });

  it("contains the required identity, checks, and partial unique index", () => {
    expect(migration).toContain(
      '"stt" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 2570) NOT NULL',
    );
    expect(migration).toContain(
      "CHECK (\"identity_status\" IN ('RESOLVED', 'UNRESOLVED'))",
    );
    expect(migration).toContain(
      "CHECK (\"origin\" IN ('LEGACY_IMPORT', 'APPROVED_SUBMISSION'))",
    );
    expect(migration).toContain('CHECK ("version_no" >= 1)');
    expect(migration).toMatch(
      /CREATE UNIQUE INDEX "ueb_core_data_source_submission_id_record_uid_key"[\s\S]*?WHERE "source_submission_id" IS NOT NULL;/u,
    );
  });

  it("blocks update, delete, and truncate on all append-only tables", () => {
    expect(migration).toContain(
      'CREATE FUNCTION "reject_append_only_mutation"()',
    );

    for (const table of ["ueb_core_data", "import_run", "workflow_event"]) {
      expect(migration).toContain(
        `BEFORE UPDATE OR DELETE ON "${table}"\nFOR EACH ROW`,
      );
      expect(migration).toContain(
        `BEFORE TRUNCATE ON "${table}"\nFOR EACH STATEMENT`,
      );
    }
  });

  it("does not add lecturer or authentication models", () => {
    expect(schema).not.toMatch(/^model (Lecturer|User|Account|Session)\b/mu);
  });
});
