-- CreateTable
CREATE TABLE "ueb_core_data" (
    "stt" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 2570) NOT NULL,
    "don_vi_phu_trach_hoc_phan" TEXT,
    "bo_mon_phu_trach_hoc_phan" TEXT,
    "khoi_kien_thuc" TEXT,
    "ma_hoc_phan" TEXT,
    "ten_hoc_phan" TEXT,
    "ten_giang_vien" TEXT,
    "ma_so_can_bo" TEXT,
    "email_tai_khoan_vnu" TEXT,
    "bo_mon" TEXT,
    "don_vi" TEXT,
    "core_1_2_3" TEXT,
    "tc1_tro_giang" TEXT,
    "tc2_sh_chuyen_mon" TEXT,
    "tc3_tong_hop" TEXT,
    "tc3_1_nganh_tot_nghiep_phu_hop" TEXT,
    "tc3_2_bien_soan_de_cuong_giao_trinh" TEXT,
    "tc3_3_chu_nhiem_de_tai_nckh_lien_quan" TEXT,
    "tc3_4_bai_bao_lien_quan" TEXT,
    "tc4_giang_thu" TEXT,
    "lecturer_uid" UUID NOT NULL,
    "record_uid" UUID NOT NULL,
    "snapshot_id" UUID NOT NULL,
    "version_no" INTEGER NOT NULL,
    "identity_status" VARCHAR(16) NOT NULL,
    "source_row_number" INTEGER NOT NULL,
    "source_row_checksum" CHAR(64) NOT NULL,
    "source_import_run_id" UUID NOT NULL,
    "source_submission_id" UUID,
    "approval_unit" TEXT,
    "origin" VARCHAR(32) NOT NULL,
    "approved_by" UUID,
    "approved_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ueb_core_data_pkey" PRIMARY KEY ("stt"),
    CONSTRAINT "ueb_core_data_version_no_check" CHECK ("version_no" >= 1),
    CONSTRAINT "ueb_core_data_identity_status_check" CHECK ("identity_status" IN ('RESOLVED', 'UNRESOLVED')),
    CONSTRAINT "ueb_core_data_origin_check" CHECK ("origin" IN ('LEGACY_IMPORT', 'APPROVED_SUBMISSION'))
);

-- CreateTable
CREATE TABLE "import_run" (
    "id" UUID NOT NULL,
    "source_filename" TEXT NOT NULL,
    "source_sha256" CHAR(64) NOT NULL,
    "source_sheet" TEXT NOT NULL,
    "source_contract_version" VARCHAR(32) NOT NULL,
    "source_row_count" INTEGER NOT NULL,
    "source_min_stt" INTEGER NOT NULL,
    "source_max_stt" INTEGER NOT NULL,
    "canonical_dataset_sha256" CHAR(64) NOT NULL,
    "report" JSONB NOT NULL,
    "imported_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "import_run_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workflow_event" (
    "event_id" UUID NOT NULL,
    "submission_id" UUID NOT NULL,
    "parent_submission_id" UUID,
    "event_type" VARCHAR(64) NOT NULL,
    "lecturer_uid" UUID NOT NULL,
    "approval_unit" TEXT,
    "payload" JSONB NOT NULL,
    "actor_user_id" UUID,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workflow_event_pkey" PRIMARY KEY ("event_id")
);

-- CreateIndex
CREATE INDEX "ueb_core_data_lecturer_uid_stt_idx" ON "ueb_core_data"("lecturer_uid", "stt" DESC);

-- CreateIndex
CREATE INDEX "ueb_core_data_snapshot_id_idx" ON "ueb_core_data"("snapshot_id");

-- CreateIndex
CREATE INDEX "ueb_core_data_ma_so_can_bo_idx" ON "ueb_core_data"("ma_so_can_bo");

-- CreateIndex
CREATE INDEX "ueb_core_data_email_tai_khoan_vnu_idx" ON "ueb_core_data"("email_tai_khoan_vnu");

-- CreateIndex
CREATE INDEX "ueb_core_data_approval_unit_idx" ON "ueb_core_data"("approval_unit");

-- CreateIndex
CREATE UNIQUE INDEX "ueb_core_data_record_uid_snapshot_id_key" ON "ueb_core_data"("record_uid", "snapshot_id");

-- CreateIndex
CREATE UNIQUE INDEX "ueb_core_data_lecturer_uid_version_no_record_uid_key" ON "ueb_core_data"("lecturer_uid", "version_no", "record_uid");

-- CreateIndex
CREATE UNIQUE INDEX "ueb_core_data_source_submission_id_record_uid_key"
ON "ueb_core_data"("source_submission_id", "record_uid")
WHERE "source_submission_id" IS NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "import_run_source_sha256_key" ON "import_run"("source_sha256");

-- CreateIndex
CREATE INDEX "workflow_event_submission_id_created_at_idx" ON "workflow_event"("submission_id", "created_at");

-- AddForeignKey
ALTER TABLE "ueb_core_data" ADD CONSTRAINT "ueb_core_data_source_import_run_id_fkey" FOREIGN KEY ("source_import_run_id") REFERENCES "import_run"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AppendOnlyFunction
CREATE FUNCTION "reject_append_only_mutation"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Operation % is not allowed on append-only table %', TG_OP, TG_TABLE_NAME;
END;
$$;

-- AppendOnlyTriggers: ueb_core_data
CREATE TRIGGER "ueb_core_data_reject_update_delete"
BEFORE UPDATE OR DELETE ON "ueb_core_data"
FOR EACH ROW
EXECUTE FUNCTION "reject_append_only_mutation"();

CREATE TRIGGER "ueb_core_data_reject_truncate"
BEFORE TRUNCATE ON "ueb_core_data"
FOR EACH STATEMENT
EXECUTE FUNCTION "reject_append_only_mutation"();

-- AppendOnlyTriggers: import_run
CREATE TRIGGER "import_run_reject_update_delete"
BEFORE UPDATE OR DELETE ON "import_run"
FOR EACH ROW
EXECUTE FUNCTION "reject_append_only_mutation"();

CREATE TRIGGER "import_run_reject_truncate"
BEFORE TRUNCATE ON "import_run"
FOR EACH STATEMENT
EXECUTE FUNCTION "reject_append_only_mutation"();

-- AppendOnlyTriggers: workflow_event
CREATE TRIGGER "workflow_event_reject_update_delete"
BEFORE UPDATE OR DELETE ON "workflow_event"
FOR EACH ROW
EXECUTE FUNCTION "reject_append_only_mutation"();

CREATE TRIGGER "workflow_event_reject_truncate"
BEFORE TRUNCATE ON "workflow_event"
FOR EACH STATEMENT
EXECUTE FUNCTION "reject_append_only_mutation"();
